config/routes.rb
Thundercloud::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users

  root to: "artists#index"

  match "/blog" => "static_pages#blog", via: :get
  match "/about" => "static_pages#about", via: :get

  resources :artists
  resources :products, only: [:index, :show]
  resources :line_items, only: [:create, :destroy]
  resources :carts, only: [:show] do
    member do
      get :checkout
      get :confirm
    end
  end

  resources :orders, only: [:show]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, session)

    user ||= User.new

    if user.has_role?(:admin)
      can :manage, :all
    else
      can :read, Product
      can :read, Artist
      can :read, Album
      can :read, Order #TODO e-mail order receipt
      can :create, LineItem
      can :destroy, LineItem do |item|
        item.itemable.token == session[:cart_token]
      end
      can [:read, :checkout, :confirm], Cart do |cart|
        cart.token == session[:cart_token]
      end
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist

  has_attached_file :image, :styles => { :medium => "450x450>", :small => "200x200>" }
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
  has_many :products

  default_scope order('name ASC')

  has_attached_file :image, :styles => { :large => "600x600>" , :medium => "300x300>", :small => "200x200>" }
end

app/models/cart.rb
#orders are all done in cent values so we can use integers
class Cart < ActiveRecord::Base
  has_many :line_items, as: :itemable, dependent: :destroy

  before_create :generate_token

  def has_product?(product)
    line_items.where(product_id: product.id).any?
  end

  def line_item_by_product(product)
    line_items.find_by_product_id(product.id)
  end

  def update_total
    total = 0
    line_items.each do |item|
      total += (item.price * item.quantity)
    end
    self.order_total = total
    save
  end

  def to_param
    token
  end

  private

  def generate_token
    self.token = loop do
      random_token = SecureRandom.hex(4)
      break random_token unless Cart.where(token: random_token).exists?
    end
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :itemable, polymorphic: true
  belongs_to :product

  after_create :update_order_total
  after_update :update_order_total
  after_destroy :update_order_total

  def update_order_total
    itemable.update_total if itemable_type == "Cart"
  end

  def self.construct_from_product(cart, product)
    if cart.has_product?(product)
      line_item = cart.line_item_by_product(product)
      line_item.quantity += 1
    else
      line_item = LineItem.new
      line_item.product_id = product.id
      line_item.itemable_id = cart.id
      line_item.itemable_type = "Cart"
      line_item.price = product.price
      line_item.quantity = 1
    end
    line_item
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, as: :itemable

  before_create :generate_token

  def self.construct_from_cart(cart)
    new_order = Order.new
    new_order.total = cart.order_total
    new_order.save
    new_order.populate_line_items(cart)

    new_order
  end

  def populate_line_items(cart)
    cart.line_items.each do |item|
      item.itemable_type = self.class.name
      item.itemable_id = self.id
      item.save
    end
    cart.reload.update_total
  end

  private

  #TODO
  #This method is a duplicate of the one in cart.rb, factor it out to a module maybe?
  def generate_token
    self.token = loop do
      random_token = SecureRandom.hex(4)
      break random_token unless Order.where(token: random_token).exists?
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :artist

  validates_presence_of :name, :description, :price

  scope :released, -> { where(upcoming: false) }

  has_attached_file :image, :styles => { :medium => "300x300>", :small => "200x200>" }
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  rolify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_cart

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to products_path, :alert => exception.message
  end

  def current_ability
    @current_ability ||= Ability.new(current_user, session)
  end

  def authenticate_admin_user!
    redirect_to root_path, notice: "You are not an admin." if !current_user.try(:has_role?, :admin)
    authenticate_user!
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  load_and_authorize_resource

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums
    @products = @artist.products
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  load_and_authorize_resource

  def create
    product = Product.find(params[:product_id])
    if LineItem.construct_from_product(current_cart, product).save
      redirect_to cart_path(current_cart)
    else
      redirect_to products_path, notice: "Something went wrong."
    end
  end

  def destroy
    line_item = LineItem.find(params[:id])
    if line_item.itemable_type == "Cart"
      cart = line_item.itemable
      line_item.destroy
      redirect_to cart_path(cart)
    else
      redirect_to root_path, notice: "You cannot delete line items from an order."
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def index
    @products = Product.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_authorization_check

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cents_to_dollars(price)
    price / 100
  end

  def price_in_dollars(price)
    number_to_currency(cents_to_dollars(price))
  end

  def is_shop_page?(params)
    params[:controller] == "products" || params[:controller] == "carts"
  end

  def is_artist_page?(params)
    params[:controller] == "artists"
  end

  def is_about_page?(params)
    params[:controller] == "static_pages" && params[:action] == "about"
  end

  def is_contact_page?(params)
    params[:controller] == "static_pages" && params[:action] == "contact"
  end
end

app/views/artists/_form.haml
= form_for @artist do |f|
  = f.label :name
  = f.text_field :name

  = f.label :description
  = f.text_field :description

  = f.label :image
  = f.file_field :image

  = f.submit

app/views/artists/edit.haml
= render 'form'

app/views/artists/index.haml
.artists-wrapper
  - @artists.each do |artist|
    .artist
      .image= link_to(image_tag(artist.image.url(:medium)), artist_path(artist))
      .name= link_to artist.name, artist
      .description= artist.description

app/views/artists/new.haml
= render 'form'

app/views/artists/show.haml
.artist-show
  .image= image_tag @artist.image.url(:large)
  .name= @artist.name
  .desc= @artist.description

%h2 Albums
.artist-albums
  - unless @albums.empty?
    .album
      - @albums.each do |album|
        .image= link_to(image_tag(album.image.url(:medium)), album.bandcamp_link)
        .name= album.name
  - else
    %p None yet, but coming soon!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thundercloud Records</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/shared/header' %>
<%- if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<%- if flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/orders/show.haml
%h2 Order Confirmation

.order-list
  %table
    %th.name Name
    %th.quantity Quantity
    %th Price
    - @order.line_items.each do |item|
      %tr
        %td.name= item.product.name
        %td.quantity= item.quantity
        %td= price_in_dollars(item.price)

    %tr
      %td
      %td.quantity Total
      %td= price_in_dollars @order.total

%p
  Your order token is:
  =@order.token

app/views/products/index.haml
.cart
  = link_to(fa_icon("shopping-cart", class: "cart-icon"), cart_path(current_cart))
  = link_to "(#{price_in_dollars(current_cart.order_total)})", cart_path(current_cart), class: "cart-total"

.product-wrapper
  - @products.each do |product|
    .product
      .product-image= link_to(image_tag(product.image.url(:medium)), product_path(product))
      .product-name= link_to product.name, product_path(product)
      .product-price{class: product.upcoming ? "red" : ""}= product.upcoming ? "Coming Soon!" : price_in_dollars(product.price)
      .add-cart= link_to "Add to Cart", line_items_path(product_id: product), method: :post if !product.upcoming?

app/views/products/show.haml
= @product.name
Price:
= @product.price

app/views/shared/_header.haml
%h1 Thundercloud Records
%ul.nav
  %li= link_to "Artists", artists_path, class: (is_artist_page?(params) ? "selected" : nil)
  %li= link_to "About", about_path, class: (is_about_page?(params) ? "selected" : nil)

app/views/static_pages/about.haml
.about
  Thundercloud Records is a small independent record label currently based in the Echo Park neighborhood of Los Angeles.
  Our mission is to help talented musicians release their music in physical formats.

.contact
  We are currently accepting demo submissions.

  .label Demo submissions:
  demos@thundercloudrecords.com

  .label General information:
  evan@thundercloudrecords.com